//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project1Entities : DbContext
    {
        public Project1Entities()
            : base("name=Project1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<service> services { get; set; }
        public DbSet<user_details> user_details { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<offer> offers { get; set; }
        public DbSet<offer_images> offer_images { get; set; }
        public DbSet<service_images> service_images { get; set; }
        public DbSet<request> requests { get; set; }
    }
}
