//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class offer
    {
        public offer()
        {
            this.usersliked = new HashSet<user>();
            this.offer_images = new HashSet<offer_images>();
            this.requests = new HashSet<request>();
        }
    
        public int offer_id { get; set; }
        public int service_id { get; set; }
        public string name { get; set; }
        public Nullable<int> min_cost { get; set; }
        public Nullable<int> max_cost { get; set; }
        public Nullable<int> quantity { get; set; }
        public string description { get; set; }
        public Nullable<bool> requestable { get; set; }
    
        public virtual service service { get; set; }
        public virtual ICollection<user> usersliked { get; set; }
        public virtual ICollection<offer_images> offer_images { get; set; }
        public virtual ICollection<request> requests { get; set; }
    }
}
