//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int user_id { get; set; }
        public int offer_id { get; set; }
        public Nullable<System.DateTime> requestDate { get; set; }
        public string response { get; set; }
        public Nullable<System.DateTime> responseDate { get; set; }
        public string responseMassage { get; set; }
        public string requsetMassage { get; set; }
        public Nullable<int> rating { get; set; }
        public string comment { get; set; }
    
        public virtual offer offer { get; set; }
        public virtual user user { get; set; }
    }
}
